services:
  studio:
    build: .
    container_name: chronicle-studio
    ports:
      - "8080:8080"
    environment:
      - SECRET_KEY=${SECRET_KEY}
    restart: always
    volumes:
      - studio_data:/app/data

volumes:
  studio_data:
