services:
  bootstrap-server:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: rdap-bootstrap
    restart: unless-stopped
    ports:
      - "5004:8000"
    volumes:
      - ./bootstrap_server/data:/app/bootstrap_server/data
    networks:
      - rdap-network

networks:
  rdap-network:
    driver: bridge
