name: Deploy to Mini PC

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            powershell -Command "$env:DOCKER_BUILDKIT=0;$env:DOCKER_CONFIG='C:\Users\onmis\.docker';cd C:\Users\onmis\project;git fetch origin main;git reset --hard origin/main;cd gallery;docker-compose build --no-cache;docker-compose up -d;cd ../portal;docker-compose build --no-cache;docker-compose up -d;git log -1"